name: Deploy Repository

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      directory:
        required: true
        type: string
    secrets:
      SERVER_HOST:
        required: true
      SERVER_USERNAME:
        required: true
      SERVER_PASSWORD:
        required: true
      DIR:
        required: true

jobs:
  connect_ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup SSH connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd ${{ github.event.inputs.directory }}

  enable_maintenance:
    runs-on: ubuntu-latest
    needs: connect_ssh
    steps:
      - name: Enable Maintenance Mode
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            echo "Blog maintenance activate"
            cd ${{ github.event.inputs.directory }}
            wp maintenance-mode activate

  git_checkout:
    runs-on: ubuntu-latest
    needs: enable_maintenance
    steps:
      - name: Git checkout
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            echo "Resetting repository state"
            cd ${{ github.event.inputs.directory }}
            echo "git fetch"
            git fetch origin
            echo "git reset"
            git reset --hard
            echo "git checkout"
            git checkout -f ${{ github.event.inputs.branch }}
            echo "git pull"
            git pull origin ${{ github.event.inputs.branch }}

  disable_maintenance:
    runs-on: ubuntu-latest
    needs: git_checkout
    steps:
      - name: Enable Maintenance Mode
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            echo "Blog maintenance deactivate"
            cd ${{ github.event.inputs.directory }}
            wp maintenance-mode deactivate

