name: Deploy Repository

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      use_composer1:
        required: false
        type: string
        default: 'false'
    secrets:
      SERVER_HOST:
        required: true
      SERVER_USERNAME:
        required: true
      SERVER_PASSWORD:
        required: true
      DIR:
        required: true

jobs:
  connect_ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup SSH connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd ${{ vars.DIR }}

  git_checkout:
    runs-on: ubuntu-latest
    needs: connect_ssh
    steps:
      - name: Git checkout
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            echo "Resetting repository state"
            cd ${{ vars.DIR }}
            echo "git fetch"
            git fetch origin
            echo "git reset"
            git reset --hard
            echo "git checkout"
            git checkout -f ${{ github.event.inputs.branch }}
            echo "git pull"
            git pull origin ${{ github.event.inputs.branch }}

  enable_maintenance:
    runs-on: ubuntu-latest
    needs: git_checkout
    steps:
      - name: Enable Maintenance Mode
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            echo "Resetting repository state"
            cd ${{ vars.DIR }}
            php -d memory_limit=3096M bin/magento maintenance:enable

  composer_install:
    runs-on: ubuntu-latest
    needs: enable_maintenance
    steps:
      - name: Composer Install
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            echo "Run Composer install"
            cd ${{ vars.DIR }}
            if [ "${{ github.event.inputs.use_composer1 }}" = "true" ]; then
              composer1 install
            else
              composer install
            fi

  magento_upgrade:
    runs-on: ubuntu-latest
    needs: composer_install
    steps:
      - name: Run bin/magento setup:upgrade
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            echo "Run bin/magento setup:upgrade"
            cd ${{ vars.DIR }}
            php -d memory_limit=3096M bin/magento maintenance:enable

  di_and_static_compile:
    runs-on: ubuntu-latest
    needs: magento_upgrade
    steps:
      - name: Run bin/magento setup:di:compile and setup:static-content:deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            echo "Run bin/magento setup:di:compile and setup:static-content:deploy"
            cd ${{ vars.DIR }}
            rm -rf generated/*
            php -d memory_limit=3096M bin/magento setup:di:compile
            rm -rf pub/static/*
            php -d memory_limit=3096M bin/magento setup:static-content:deploy -f en_GB en_US
  
  

  disable_maintenance:
    runs-on: ubuntu-latest
    needs: di_and_static_compile
    steps:
      - name: Disable Maintenance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            echo "Disable maintenance mode"
            cd ${{ vars.DIR }}
            php -d memory_limit=3096M bin/magento maintenance:disable
