name: Restore DB from staging to live

on:
  workflow_call:
    inputs:
      live_directory:
        required: true
        type: string
      staging_directory:
        required: true
        type: string
    secrets:
      SERVER_HOST:
        required: true
      SERVER_USERNAME:
        required: true
      SERVER_PASSWORD:
        required: true
      DIR:
        required: true


jobs:
  parse_db_conn_staging:
    runs-on: ubuntu-latest
    steps:
      - name: Parse DB Connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd ${{ github.event.inputs.staging_directory }}
            php -r "\$c=require 'app/etc/env.php'; 
                     \$d=\$c['db']['connection']['default'];
                     \$envContent = 'STAGING_DB_NAME='.\$d['dbname'].\"\n\".
                                   'STAGING_DB_USER='.\$d['username'].\"\n\".
                                   'STAGING_DB_PASS='.\$d['password'].\"\n\";
                     file_put_contents('/tmp/staging_db_config.env', \$envContent);"

  parse_db_conn_live:
    runs-on: ubuntu-latest
    steps:
      - name: Parse DB Connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd ${{ github.event.inputs.live_directory }}
            php -r "\$c=require 'app/etc/env.php'; 
                     \$d=\$c['db']['connection']['default'];
                     \$envContent = 'LIVE_DB_NAME='.\$d['dbname'].\"\n\".
                                   'LIVE_DB_USER='.\$d['username'].\"\n\".
                                   'LIVE_DB_PASS='.\$d['password'].\"\n\";
                     file_put_contents('/tmp/live_db_config.env', \$envContent);"

  create_staging_db_backup:
    runs-on: ubuntu-latest
    needs:
      - parse_db_conn_live
      - parse_db_conn_staging

    steps:
      - name: Create Staging DB backup
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            set -a
            source /tmp/staging_db_config.env
            set +a
            cd ${{ github.event.inputs.staging_directory }}
            mysqldump -u${STAGING_DB_USER} -p${STAGING_DB_PASS} ${STAGING_DB_NAME} > currentLiveDBDump.sql
            cat currentLiveDBDump.sql | sed -e 's/DEFINER[ ]*=[ ]*[^*]*\*/\*/' > currentLiveDBDumpWithoutDefiner.sql
