name: Restore DB from staging to live

on:
  workflow_call:
    inputs:
      live_directory:
        required: true
        type: string
      staging_directory:
        required: true
        type: string
    secrets:
      SERVER_HOST:
        required: true
      SERVER_USERNAME:
        required: true
      SERVER_PASSWORD:
        required: true
      DIR:
        required: true


jobs:
  connect_ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup SSH connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd ${{ github.event.inputs.live_directory }}
  parse_db_conn_staging:
    runs-on: ubuntu-latest
    needs: connect_ssh
    steps:
      - name: Parse DB Connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd ${{ github.event.inputs.staging_directory }}
            PHP_SCRIPT=$(cat << 'EOF'
            <?php
            $config = require '${{ github.workspace }}/app/etc/env.php';
            $dbConfig = $config['db']['connection']['default'];
            echo "DB_NAME=" . $dbConfig['dbname'] . "\n";
            echo "DB_USER=" . $dbConfig['username'] . "\n";
            echo "DB_PASS=" . $dbConfig['password'] . "\n";
            ?>
            EOF
            )
            
            # Execute PHP script and set outputs
            php -r "$PHP_SCRIPT" >> $GITHUB_OUTPUT
            
  staging_magento_dump:
    runs-on: ubuntu-latest
    needs: parse_db_conn_staging

    steps:
      - name: Create Staging DB dump
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
              echo "${{ steps.extract-creds.outputs.DB_NAME }} ${{ steps.extract-creds.outputs.DB_USER }} ${{ steps.extract-creds.outputs.DB_PASS }}"
