name: Restore DB from staging to live

on:
  workflow_call:
    inputs:
      live_directory:
        required: true
        type: string
      staging_directory:
        required: true
        type: string
    secrets:
      SERVER_HOST:
        required: true
      SERVER_USERNAME:
        required: true
      SERVER_PASSWORD:
        required: true
      DIR:
        required: true


jobs:
  connect_ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd ${{ github.event.inputs.live_directory }}

  parse_db_conn_staging:
    runs-on: ubuntu-latest
    outputs:
      db_name: ${{ steps.extract-creds.outputs.db_name }}
      db_user: ${{ steps.extract-creds.outputs.db_user }}
      db_pass: ${{ steps.extract-creds.outputs.db_pass }}
    needs: connect_ssh
    steps:
      - name: Parse DB Connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd ${{ github.event.inputs.staging_directory }}
            php -r "\$c=require 'app/etc/env.php'; \$d=\$c['db']['connection']['default']; echo 'db_name='.\$d['dbname'].\"\n\"; echo 'db_user='.\$d['username'].\"\n\"; echo 'db_pass='.\$d['password'].\"\n\";"
            
  staging_magento_dump:
    runs-on: ubuntu-latest
    needs: parse_db_conn_staging

    steps:
      - name: Create Staging DB dump
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            echo "DB Name: ${{ needs.parse_db_conn_staging.outputs.db_name }}"
            echo "DB User: ${{ needs.parse_db_conn_staging.outputs.db_user }}"
            echo "DB Pass: ${{ needs.parse_db_conn_staging.outputs.db_pass }}"
