name: Restore DB from staging to live

on:
  workflow_call:
    inputs:
      live_directory:
        required: true
        type: string
      staging_directory:
        required: true
        type: string
    secrets:
      SERVER_HOST:
        required: true
      SERVER_USERNAME:
        required: true
      SERVER_PASSWORD:
        required: true
      DIR:
        required: true


jobs:
  restore_db_from_live_to_staging:
    runs-on: ubuntu-latest
    steps:
      - name: Parse Staging DB Connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd ${{ github.event.inputs.staging_directory }}
            eval $(php -r "\$c=require 'app/etc/env.php';\$d=\$c['db']['connection']['default'];foreach(['dbname','username','password'] as \$k){echo 'export STAGING_DB_'.strtoupper(\$k).'='.trim(\$d[\$k]).\"\n\";}")

      - name: Parse Live DB Connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd ${{ github.event.inputs.live_directory }}
            eval $(php -r "\$c=require 'app/etc/env.php';\$d=\$c['db']['connection']['default'];foreach(['dbname','username','password'] as \$k){echo 'export LIVE_DB_'.strtoupper(\$k).'='.trim(\$d[\$k]).\"\n\";}")

      - name: Create Current Staging Dump
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            echo $STAGING_DB_DBNAME
            echo $LIVE_DB_DBNAME
            echo $STAGING_DB_PASS
            echo $LIVE_DB_PASS
