name: Restore DB from staging to live

on:
  workflow_call:
    inputs:
      live_directory:
        required: true
        type: string
      staging_directory:
        required: true
        type: string
    secrets:
      SERVER_HOST:
        required: true
      SERVER_USERNAME:
        required: true
      SERVER_PASSWORD:
        required: true
      DIR:
        required: true


jobs:
  connect_ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd ${{ github.event.inputs.live_directory }}

  parse_db_conn_staging:
    runs-on: ubuntu-latest
    needs: connect_ssh
    steps:
      - name: Parse DB Connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd ${{ github.event.inputs.staging_directory }}
            php -r "\$c=require 'app/etc/env.php'; 
                     \$d=\$c['db']['connection']['default'];
                     \$envContent = 'DB_NAME='.\$d['dbname'].\"\n\".
                                   'DB_USER='.\$d['username'].\"\n\".
                                   'DB_PASS='.\$d['password'].\"\n\";
                     file_put_contents('/tmp/db_config.env', \$envContent);"
            
            echo "=== env file ==="
            cat /tmp/db_config.env
            echo "======================================"
            
  staging_magento_dump:
    runs-on: ubuntu-latest
    needs: parse_db_conn_staging

    steps:
      - name: Create Staging DB dump
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            set -a
            source /tmp/db_config.env
            set +a
            echo "Database: $DB_NAME"
            echo "User: $DB_USER"
            echo "Pass: $DB_PASS"
