name: Restore DB from staging to live

on:
  workflow_call:
    inputs:
      live_directory:
        required: true
        type: string
      staging_directory:
        required: true
        type: string
      blog_theme_name:
        required: true
        type: string
    secrets:
      SERVER_HOST:
        required: true
      SERVER_USERNAME:
        required: true
      SERVER_PASSWORD:
        required: true
      DIR:
        required: true

jobs:
  parse_db_conn_staging:
    runs-on: ubuntu-latest
    steps:
      - name: Parse DB Connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd ${{ github.event.inputs.staging_directory }}
            php -r "\$c=require 'wp-config.php'; 
                     \$envContent = 'STAGING_BLOG_DB_NAME='. DB_NAME .\"\n\".
                                   'STAGING_BLOG_DB_USER='.DB_USER.\"\n\".
                                   'STAGING_BLOG_DB_PASS='.DB_PASSWORD.\"\n\";
                     file_put_contents('/tmp/staging_blog_db_config.env', \$envContent);"
